root: true
env:
  node: true
parser: '@typescript-eslint/parser'
plugins:
  - '@typescript-eslint'
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/eslint-recommended'
  - 'plugin:@typescript-eslint/strict'
  - 'prettier'
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project:
    - tsconfig.json
